name: X-BE CICD

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Docker Hub Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t your-dockerhub-username/your-app-image-name .

      - name: Push Docker image
        run: docker push your-dockerhub-username/your-app-image-name

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
        script: |
          docker pull your-dockerhub-username/your-app-image-name
          docker stop app || true
          docker rm app || true
          docker run -d --name app -p 8080:8080 your-dockerhub-username/your-app-image-name
